# -*- coding: utf-8 -*-
import os

BASE = r"c:\Users\Sarishma\Project-Xeno\xenon-backend\src\main\java\com\xenocrm"

def w(path, content):
    full = os.path.join(BASE, path.replace("/", os.sep))
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")
    print("  wrote: " + path)

print("=== 1. ENTITIES ===")

w("customer/entity/CustomerEntity.java", '''\
package com.xenocrm.customer.entity;

import com.xenocrm.customer.enums.CustomerGender;
import com.xenocrm.customer.enums.PreferredChannel;
import io.hypersistence.utils.hibernate.type.array.StringArrayType;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.Type;
import org.hibernate.type.SqlTypes;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * CustomerEntity -- JPA entity mapping to the `customers` table.
 * Layer: Domain Entity
 * Purpose: Represents the core identity record for every shopper.
 * Relationships: OneToOne CustomerMetricsEntity; OneToMany OrderEntity.
 */
@Entity
@Table(name = "customers")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class CustomerEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id")
    private UUID id;                            // PRIMARY KEY, generated by DB

    @Column(name = "external_id", unique = true)
    private String externalId;                  // Brand own customer ID -- nullable, UNIQUE

    @Column(name = "email", unique = true)
    private String email;                       // Customer email -- nullable, UNIQUE

    @Column(name = "phone")
    private String phone;                       // E.164 format e.g. +919876543210 -- nullable

    @Column(name = "whatsapp_number")
    private String whatsappNumber;              // WhatsApp number if different from phone -- nullable

    @Column(name = "name", nullable = false)
    private String name;                        // Full name -- required

    @Column(name = "gender")
    private CustomerGender gender;              // CHECK IN (male,female,other,unknown) DEFAULT unknown

    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;              // Date of birth -- nullable

    @Column(name = "city")
    private String city;                        // City name -- nullable

    @Column(name = "state")
    private String state;                       // State/province -- nullable

    @Column(name = "country")
    private String country;                     // ISO country code DEFAULT IN

    @Type(StringArrayType.class)
    @Column(name = "tags", columnDefinition = "text[]")
    private String[] tags;                      // TEXT[] DEFAULT {}

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "custom_attributes", columnDefinition = "jsonb")
    private Map<String, Object> customAttributes; // JSONB -- brand-specific metadata

    @Column(name = "preferred_channel")
    private PreferredChannel preferredChannel;  // CHECK IN (email,whatsapp,sms,rcs)

    @Type(StringArrayType.class)
    @Column(name = "opt_out_channels", columnDefinition = "text[]")
    private String[] optOutChannels;            // TEXT[] -- channels this customer has opted out from

    @Column(name = "is_globally_opted_out", nullable = false)
    private boolean isGloballyOptedOut;         // DEFAULT FALSE -- skip entirely if true

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    @OneToOne(mappedBy = "customer", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private CustomerMetricsEntity metrics;      // computed metrics -- lazy loaded

    @OneToMany(mappedBy = "customer", fetch = FetchType.LAZY)
    private List<com.xenocrm.order.entity.OrderEntity> orders; // purchase history -- lazy loaded
}
''')

w("customer/entity/CustomerMetricsEntity.java", '''\
package com.xenocrm.customer.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * CustomerMetricsEntity -- JPA entity mapping to the `customer_metrics` table.
 * Layer: Domain Entity
 * Purpose: Computed RFM + behaviour + engagement metrics for a customer.
 * Relationships: OneToOne mapped by CustomerEntity via @MapsId.
 */
@Entity
@Table(name = "customer_metrics")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CustomerMetricsEntity {

    @Id
    @Column(name = "customer_id")
    private UUID customerId;                    // PRIMARY KEY = customers.id -- uses @MapsId

    @Column(name = "recency_days")
    private Integer recencyDays;                // Days since most recent order -- nullable

    @Column(name = "frequency")
    private Integer frequency;                  // Total number of orders across all time -- nullable

    @Column(name = "monetary_total", precision = 12, scale = 2)
    private BigDecimal monetaryTotal;           // Sum of all order total_amount -- nullable

    @Column(name = "monetary_avg_order", precision = 12, scale = 2)
    private BigDecimal monetaryAvgOrder;        // Average order value -- nullable

    @Column(name = "rfm_score", precision = 4, scale = 2)
    private BigDecimal rfmScore;                // Composite RFM score 1-5 -- nullable

    @Column(name = "total_orders_last_30d")
    private Integer totalOrdersLast30d;         // Orders in last 30 days DEFAULT 0

    @Column(name = "total_orders_last_90d")
    private Integer totalOrdersLast90d;         // Orders in last 90 days DEFAULT 0

    @Column(name = "avg_days_between_orders", precision = 6, scale = 2)
    private BigDecimal avgDaysBetweenOrders;    // Average days between consecutive orders -- nullable

    @Column(name = "favourite_category_id")
    private UUID favouriteCategoryId;           // FK to product_categories.id -- nullable

    @Column(name = "favourite_channel")
    private String favouriteChannel;            // Most used channel: web,app,store -- nullable

    @Column(name = "clv_predicted", precision = 12, scale = 2)
    private BigDecimal clvPredicted;            // Predicted 12-month CLV -- nullable

    @Column(name = "churn_probability", precision = 5, scale = 4)
    private BigDecimal churnProbability;        // Probability 0-1 of churning -- nullable

    @Column(name = "email_open_rate", precision = 5, scale = 4)
    private BigDecimal emailOpenRate;           // Email open rate DEFAULT 0

    @Column(name = "email_click_rate", precision = 5, scale = 4)
    private BigDecimal emailClickRate;          // Email click rate DEFAULT 0

    @Column(name = "whatsapp_read_rate", precision = 5, scale = 4)
    private BigDecimal whatsappReadRate;        // WhatsApp read rate DEFAULT 0

    @Column(name = "sms_click_rate", precision = 5, scale = 4)
    private BigDecimal smsClickRate;            // SMS click rate DEFAULT 0

    @Column(name = "last_computed_at", nullable = false)
    private OffsetDateTime lastComputedAt;      // When these metrics were last recalculated

    @OneToOne(fetch = FetchType.LAZY)
    @MapsId
    @JoinColumn(name = "customer_id")
    private CustomerEntity customer;            // The customer these metrics belong to
}
''')

w("product/entity/ProductEntity.java", '''\
package com.xenocrm.product.entity;

import io.hypersistence.utils.hibernate.type.array.StringArrayType;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.Type;
import org.hibernate.type.SqlTypes;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Map;
import java.util.UUID;

/**
 * ProductEntity -- JPA entity mapping to the `products` table.
 * Layer: Domain Entity
 * Purpose: SKU-level catalog record with price, category, tags and attributes.
 */
@Entity
@Table(name = "products")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class ProductEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id")
    private UUID id;

    @Column(name = "sku", unique = true, nullable = false)
    private String sku;                         // UNIQUE NOT NULL

    @Column(name = "name", nullable = false)
    private String name;                        // NOT NULL

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private ProductCategoryEntity category;     // FK to product_categories.id -- nullable

    @Column(name = "price", precision = 12, scale = 2, nullable = false)
    private BigDecimal price;                   // NUMERIC(12,2) NOT NULL CHECK >= 0

    @Column(name = "currency", nullable = false)
    private String currency;                    // DEFAULT INR

    @Column(name = "brand")
    private String brand;                       // nullable

    @Type(StringArrayType.class)
    @Column(name = "tags", columnDefinition = "text[]")
    private String[] tags;                      // TEXT[] DEFAULT {}

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "attributes", columnDefinition = "jsonb")
    private Map<String, Object> attributes;     // JSONB -- color, size, etc.

    @Column(name = "is_active", nullable = false)
    private boolean isActive;                   // DEFAULT TRUE

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;
}
''')

w("product/entity/ProductCategoryEntity.java", '''\
package com.xenocrm.product.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import java.util.UUID;

/**
 * ProductCategoryEntity -- JPA entity mapping to the `product_categories` table.
 * Layer: Domain Entity
 * Purpose: Taxonomy tree for product classification (e.g. electronics > phones > flagship).
 */
@Entity
@Table(name = "product_categories")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProductCategoryEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id")
    private UUID id;

    @Column(name = "name", nullable = false)
    private String name;                        // NOT NULL -- category display name

    @Column(name = "slug", unique = true, nullable = false)
    private String slug;                        // UNIQUE NOT NULL -- URL-safe identifier

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id")
    private ProductCategoryEntity parentCategory; // nullable -- parent in the category tree

    @OneToMany(mappedBy = "parentCategory", fetch = FetchType.LAZY)
    private List<ProductCategoryEntity> childCategories; // sub-categories
}
''')

w("order/entity/OrderEntity.java", '''\
package com.xenocrm.order.entity;

import com.xenocrm.customer.entity.CustomerEntity;
import com.xenocrm.order.enums.OrderStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * OrderEntity -- JPA entity mapping to the `orders` table.
 * Layer: Domain Entity
 * Purpose: One row per order header; line items in order_items.
 * Relationships: ManyToOne customer; OneToMany orderItems.
 */
@Entity
@Table(name = "orders")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class OrderEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id")
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "customer_id", nullable = false)
    private CustomerEntity customer;            // FK to customers.id NOT NULL ON DELETE RESTRICT

    @Column(name = "order_number", unique = true)
    private String orderNumber;                 // UNIQUE, nullable

    @Column(name = "status")
    private OrderStatus status;                 // pending/confirmed/shipped/delivered/cancelled/returned

    @Column(name = "channel")
    private String channel;                     // web,app,store,whatsapp -- nullable

    @Column(name = "total_amount", precision = 12, scale = 2, nullable = false)
    private BigDecimal totalAmount;             // NUMERIC(12,2) NOT NULL CHECK >= 0

    @Column(name = "currency", nullable = false)
    private String currency;                    // DEFAULT INR

    @Column(name = "discount_amount", precision = 12, scale = 2)
    private BigDecimal discountAmount;          // DEFAULT 0

    @Column(name = "coupon_code")
    private String couponCode;                  // nullable

    @Column(name = "placed_at", nullable = false)
    private OffsetDateTime placedAt;            // NOT NULL DEFAULT NOW()

    @Column(name = "delivered_at")
    private OffsetDateTime deliveredAt;         // nullable

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "metadata", columnDefinition = "jsonb")
    private Map<String, Object> metadata;       // JSONB DEFAULT {}

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @Builder.Default
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<OrderItemEntity> orderItems = new ArrayList<>();

    /** Convenience method to add a line item and set the back-reference. */
    public void addItem(OrderItemEntity item) {
        orderItems.add(item);
        item.setOrder(this);
    }
}
''')

w("order/entity/OrderItemEntity.java", '''\
package com.xenocrm.order.entity;

import com.xenocrm.product.entity.ProductEntity;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.UUID;

/**
 * OrderItemEntity -- JPA entity mapping to the `order_items` table.
 * Layer: Domain Entity
 * Purpose: One row per line item inside an order.
 */
@Entity
@Table(name = "order_items")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderItemEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id")
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "order_id", nullable = false)
    private OrderEntity order;                  // FK to orders.id NOT NULL ON DELETE CASCADE

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id")
    private ProductEntity product;              // FK to products.id -- nullable

    @Column(name = "product_sku")
    private String productSku;                  // denormalised for resilience -- nullable

    @Column(name = "product_name", nullable = false)
    private String productName;                 // NOT NULL

    @Column(name = "quantity", nullable = false)
    private int quantity;                       // CHECK > 0

    @Column(name = "unit_price", precision = 12, scale = 2, nullable = false)
    private BigDecimal unitPrice;               // NUMERIC(12,2) CHECK >= 0

    @Column(name = "discount_amount", precision = 12, scale = 2)
    private BigDecimal discountAmount;          // DEFAULT 0

    @Column(name = "line_total", insertable = false, updatable = false)
    private BigDecimal lineTotal;               // GENERATED ALWAYS AS STORED: (unit_price - discount_amount)*quantity
}
''')

w("campaign/entity/CampaignEntity.java", '''\
package com.xenocrm.campaign.entity;

import com.xenocrm.campaign.enums.CampaignStatus;
import com.xenocrm.segment.entity.AudienceSegmentEntity;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * CampaignEntity -- JPA entity mapping to the `campaigns` table.
 * Layer: Domain Entity
 * Purpose: Orchestrates a marketing campaign targeting an audience segment.
 * Relationships: ManyToOne targetSegment; ManyToOne parentCampaign (self-ref).
 */
@Entity
@Table(name = "campaigns")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class CampaignEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id")
    private UUID id;

    @Column(name = "name", nullable = false)
    private String name;                        // NOT NULL

    @Column(name = "description")
    private String description;                 // nullable

    @Column(name = "status")
    private CampaignStatus status;              // draft/simulating/scheduled/running/paused/completed/cancelled/failed

    @Column(name = "goal", columnDefinition = "TEXT")
    private String goal;                        // Marketer NL goal -- nullable

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "segment_id")
    private AudienceSegmentEntity targetSegment; // FK to audience_segments.id -- nullable

    @Column(name = "scheduled_at")
    private OffsetDateTime scheduledAt;         // nullable

    @Column(name = "started_at")
    private OffsetDateTime startedAt;           // nullable

    @Column(name = "completed_at")
    private OffsetDateTime completedAt;         // nullable

    @Column(name = "timezone")
    private String timezone;                    // DEFAULT Asia/Kolkata

    @Column(name = "max_send_count")
    private Integer maxSendCount;               // nullable -- hard cap on messages dispatched

    @Column(name = "opt_out_rate_threshold", precision = 5, scale = 4)
    private BigDecimal optOutRateThreshold;     // DEFAULT 0.02 -- auto-pause if breached

    @Column(name = "created_by_agent")
    private boolean createdByAgent;             // DEFAULT FALSE

    @Column(name = "agent_session_id")
    private String agentSessionId;              // nullable -- ties back to the agent run

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_campaign_id")
    private CampaignEntity parentCampaign;      // self-referencing FK -- nullable (self-correction retries)

    // Denormalised performance counters -- ALL incremented via @Modifying @Query UPDATE
    @Column(name = "total_sent")
    private int totalSent;                      // DEFAULT 0

    @Column(name = "total_delivered")
    private int totalDelivered;                 // DEFAULT 0

    @Column(name = "total_failed")
    private int totalFailed;                    // DEFAULT 0

    @Column(name = "total_opened")
    private int totalOpened;                    // DEFAULT 0

    @Column(name = "total_read")
    private int totalRead;                      // DEFAULT 0

    @Column(name = "total_clicked")
    private int totalClicked;                   // DEFAULT 0

    @Column(name = "total_converted")
    private int totalConverted;                 // DEFAULT 0 -- orders attributed to this campaign

    @Column(name = "revenue_attributed", precision = 14, scale = 2)
    private BigDecimal revenueAttributed;       // NUMERIC(14,2) DEFAULT 0

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;
}
''')

w("variant/entity/MessageVariantEntity.java", '''\
package com.xenocrm.variant.entity;

import com.xenocrm.campaign.entity.CampaignEntity;
import com.xenocrm.channelservice.enums.MessageChannel;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Map;
import java.util.UUID;

/**
 * MessageVariantEntity -- JPA entity mapping to the `message_variants` table.
 * Layer: Domain Entity
 * Purpose: One A/B variant (copy + channel) for a campaign; MAB drives selection.
 */
@Entity
@Table(name = "message_variants")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class MessageVariantEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id")
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "campaign_id", nullable = false)
    private CampaignEntity campaign;            // FK to campaigns.id NOT NULL ON DELETE CASCADE

    @Column(name = "name", nullable = false)
    private String name;                        // NOT NULL -- e.g. Email - urgency copy A

    @Enumerated(EnumType.STRING)
    @org.hibernate.annotations.Type(io.hypersistence.utils.hibernate.type.basic.PostgreSQLEnumType.class)
    @Column(name = "channel", columnDefinition = "message_channel", nullable = false)
    private MessageChannel channel;             // Postgres ENUM -- must include columnDefinition

    @Column(name = "subject_line")
    private String subjectLine;                 // email subject -- nullable

    @Column(name = "preview_text")
    private String previewText;                 // email preview -- nullable

    @Column(name = "body_text", columnDefinition = "TEXT")
    private String bodyText;                    // plaintext/WhatsApp body -- nullable

    @Column(name = "body_html", columnDefinition = "TEXT")
    private String bodyHtml;                    // rich HTML email -- nullable

    @Column(name = "cta_text")
    private String ctaText;                     // CTA button label -- nullable

    @Column(name = "cta_url")
    private String ctaUrl;                      // destination URL -- nullable

    @Column(name = "media_url")
    private String mediaUrl;                    // image/video URL -- nullable

    @Column(name = "template_id")
    private String templateId;                  // WA Business template ID -- nullable

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "template_params", columnDefinition = "jsonb")
    private Map<String, Object> templateParams; // template placeholder values

    @Column(name = "mab_alpha", precision = 10, scale = 4)
    private BigDecimal mabAlpha;                // NUMERIC(10,4) DEFAULT 1.0 -- successes + prior 1

    @Column(name = "mab_beta", precision = 10, scale = 4)
    private BigDecimal mabBeta;                 // NUMERIC(10,4) DEFAULT 1.0 -- failures + prior 1

    @Column(name = "mab_impressions")
    private int mabImpressions;                 // DEFAULT 0 -- total deliveries recorded

    @Column(name = "mab_conversions")
    private int mabConversions;                 // DEFAULT 0 -- total clicks/conversions recorded

    @Column(name = "mab_is_active")
    private boolean mabIsActive;                // DEFAULT TRUE -- set false to disable this variant

    @Column(name = "generated_by_ai")
    private boolean generatedByAi;              // DEFAULT FALSE

    @Column(name = "generation_prompt", columnDefinition = "TEXT")
    private String generationPrompt;            // nullable -- prompt used to generate this variant

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;
}
''')

print("=== 2. DTOs ===")

w("customer/dto/CustomerCreateRequestDto.java", '''\
package com.xenocrm.customer.dto;

import com.xenocrm.customer.enums.CustomerGender;
import com.xenocrm.customer.enums.PreferredChannel;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDate;
import java.util.Map;

/** CustomerCreateRequestDto -- DTO for ingesting a new customer. Layer: DTO */
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class CustomerCreateRequestDto {
    private String externalId;
    @Email private String email;
    private String phone;
    private String whatsappNumber;
    @NotBlank private String name;
    private CustomerGender gender;
    private LocalDate dateOfBirth;
    private String city;
    private String state;
    private String country;
    private String[] tags;
    private Map<String, Object> customAttributes;
    private PreferredChannel preferredChannel;
    private String[] optOutChannels;
    private boolean isGloballyOptedOut;
}
''')

w("customer/dto/CustomerUpdateRequestDto.java", '''\
package com.xenocrm.customer.dto;

import com.xenocrm.customer.enums.CustomerGender;
import com.xenocrm.customer.enums.PreferredChannel;
import jakarta.validation.constraints.Email;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDate;
import java.util.Map;

/** CustomerUpdateRequestDto -- DTO for updating an existing customer. Layer: DTO */
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class CustomerUpdateRequestDto {
    @Email private String email;
    private String phone;
    private String whatsappNumber;
    private String name;
    private CustomerGender gender;
    private LocalDate dateOfBirth;
    private String city;
    private String state;
    private String country;
    private String[] tags;
    private Map<String, Object> customAttributes;
    private PreferredChannel preferredChannel;
    private String[] optOutChannels;
    private Boolean isGloballyOptedOut;
}
''')

w("customer/dto/CustomerResponseDto.java", '''\
package com.xenocrm.customer.dto;

import com.xenocrm.customer.enums.CustomerGender;
import com.xenocrm.customer.enums.PreferredChannel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Map;
import java.util.UUID;

/** CustomerResponseDto -- Standard API response for a customer. Layer: DTO */
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class CustomerResponseDto {
    private UUID id;
    private String externalId;
    private String email;
    private String phone;
    private String whatsappNumber;
    private String name;
    private CustomerGender gender;
    private LocalDate dateOfBirth;
    private String city;
    private String state;
    private String country;
    private String[] tags;
    private Map<String, Object> customAttributes;
    private PreferredChannel preferredChannel;
    private String[] optOutChannels;
    private boolean isGloballyOptedOut;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
}
''')

w("customer/dto/Customer360ResponseDto.java", '''\
package com.xenocrm.customer.dto;

import com.xenocrm.customer.enums.CustomerGender;
import com.xenocrm.customer.enums.PreferredChannel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Map;
import java.util.UUID;

/** Customer360ResponseDto -- 360 view: customer identity + computed metrics. Layer: DTO */
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class Customer360ResponseDto {
    private UUID id;
    private String externalId;
    private String email;
    private String phone;
    private String whatsappNumber;
    private String name;
    private CustomerGender gender;
    private LocalDate dateOfBirth;
    private String city;
    private String state;
    private String country;
    private String[] tags;
    private Map<String, Object> customAttributes;
    private PreferredChannel preferredChannel;
    private String[] optOutChannels;
    private boolean isGloballyOptedOut;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
    // Metrics from customer_metrics
    private Integer recencyDays;
    private Integer frequency;
    private BigDecimal monetaryTotal;
    private BigDecimal monetaryAvgOrder;
    private BigDecimal rfmScore;
    private Integer totalOrdersLast30d;
    private Integer totalOrdersLast90d;
    private BigDecimal avgDaysBetweenOrders;
    private UUID favouriteCategoryId;
    private String favouriteChannel;
    private BigDecimal clvPredicted;
    private BigDecimal churnProbability;
    private BigDecimal emailOpenRate;
    private BigDecimal emailClickRate;
    private BigDecimal whatsappReadRate;
    private BigDecimal smsClickRate;
    private OffsetDateTime lastComputedAt;
}
''')

w("campaign/dto/CampaignResponseDto.java", '''\
package com.xenocrm.campaign.dto;

import com.xenocrm.campaign.enums.CampaignStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

/** CampaignResponseDto -- Standard API response for a campaign. Layer: DTO */
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class CampaignResponseDto {
    private UUID id;
    private String name;
    private String description;
    private CampaignStatus status;
    private String goal;
    private UUID segmentId;
    private String segmentName;
    private OffsetDateTime scheduledAt;
    private OffsetDateTime startedAt;
    private OffsetDateTime completedAt;
    private String timezone;
    private Integer maxSendCount;
    private BigDecimal optOutRateThreshold;
    private boolean createdByAgent;
    private String agentSessionId;
    private UUID parentCampaignId;
    private int totalSent;
    private int totalDelivered;
    private int totalFailed;
    private int totalOpened;
    private int totalRead;
    private int totalClicked;
    private int totalConverted;
    private BigDecimal revenueAttributed;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
}
''')

w("campaign/dto/CampaignCreateRequestDto.java", '''\
package com.xenocrm.campaign.dto;

import com.xenocrm.campaign.enums.CampaignStatus;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

/** CampaignCreateRequestDto -- DTO for creating a new campaign. Layer: DTO */
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class CampaignCreateRequestDto {
    @NotBlank private String name;
    private String description;
    private UUID segmentId;
    private CampaignStatus status;
    private String goal;
    private OffsetDateTime scheduledAt;
    private String timezone;
    private Integer maxSendCount;
    private BigDecimal optOutRateThreshold;
}
''')

w("campaign/dto/CampaignStatusUpdateRequestDto.java", '''\
package com.xenocrm.campaign.dto;

import com.xenocrm.campaign.enums.CampaignStatus;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

/** CampaignStatusUpdateRequestDto -- DTO for changing campaign status. Layer: DTO */
@Data
public class CampaignStatusUpdateRequestDto {
    @NotNull private CampaignStatus status;
}
''')

w("campaign/dto/CampaignPerformanceSummaryDto.java", '''\
package com.xenocrm.campaign.dto;

import lombok.Data;
import java.math.BigDecimal;
import java.util.UUID;

/** CampaignPerformanceSummaryDto -- Maps v_campaign_performance view results. Layer: DTO */
@Data
public class CampaignPerformanceSummaryDto {
    private UUID id;
    private String name;
    private String status;
    private Integer totalSent;
    private Integer totalDelivered;
    private Integer totalFailed;
    private Integer totalOpened;
    private Integer totalClicked;
    private Integer totalConverted;
    private BigDecimal revenueAttributed;
    private BigDecimal deliveryRatePct;
    private BigDecimal failureRatePct;
    private BigDecimal openRatePct;
    private BigDecimal ctrPct;
    private BigDecimal conversionRatePct;
    private BigDecimal optOutRatePct;
    private String segmentName;
    private Integer segmentSize;
}
''')

w("campaign/dto/OptOutAlertDto.java", '''\
package com.xenocrm.campaign.dto;

import lombok.Data;
import java.math.BigDecimal;
import java.util.UUID;

/** OptOutAlertDto -- Maps v_opt_out_alerts view results. Layer: DTO */
@Data
public class OptOutAlertDto {
    private UUID campaignId;
    private String campaignName;
    private BigDecimal optOutRateThreshold;
    private BigDecimal currentOptOutRatePct;
    private String alertLevel;  // EXCEEDED, WARNING, OK
}
''')

w("variant/dto/MessageVariantCreateRequestDto.java", '''\
package com.xenocrm.variant.dto;

import com.xenocrm.channelservice.enums.MessageChannel;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Map;
import java.util.UUID;

/** MessageVariantCreateRequestDto -- DTO for creating a message variant. Layer: DTO */
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class MessageVariantCreateRequestDto {
    @NotNull private UUID campaignId;
    @NotBlank private String name;
    @NotNull private MessageChannel channel;
    private String subjectLine;
    private String previewText;
    private String bodyText;
    private String bodyHtml;
    private String ctaText;
    private String ctaUrl;
    private String mediaUrl;
    private String templateId;
    private Map<String, Object> templateParams;
    private boolean generatedByAi;
    private String generationPrompt;
}
''')

w("variant/dto/MessageVariantResponseDto.java", '''\
package com.xenocrm.variant.dto;

import com.xenocrm.channelservice.enums.MessageChannel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Map;
import java.util.UUID;

/** MessageVariantResponseDto -- Standard API response for a message variant. Layer: DTO */
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class MessageVariantResponseDto {
    private UUID id;
    private UUID campaignId;
    private String name;
    private MessageChannel channel;
    private String subjectLine;
    private String previewText;
    private String bodyText;
    private String bodyHtml;
    private String ctaText;
    private String ctaUrl;
    private String mediaUrl;
    private String templateId;
    private Map<String, Object> templateParams;
    private BigDecimal mabAlpha;
    private BigDecimal mabBeta;
    private int mabImpressions;
    private int mabConversions;
    private boolean mabIsActive;
    private boolean generatedByAi;
    private String generationPrompt;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
}
''')

w("variant/dto/MabStatsResponseDto.java", '''\
package com.xenocrm.variant.dto;

import lombok.Data;
import java.math.BigDecimal;
import java.util.UUID;

/** MabStatsResponseDto -- Thompson Sampling stats from v_variant_mab_stats. Layer: DTO */
@Data
public class MabStatsResponseDto {
    private UUID id;
    private UUID campaignId;
    private String name;
    private String channel;
    private BigDecimal mabAlpha;
    private BigDecimal mabBeta;
    private int mabImpressions;
    private int mabConversions;
    private BigDecimal expectedConversionRate;
    private BigDecimal ciHalfWidth95;
    private boolean mabIsActive;
    private String campaignName;
}
''')

w("order/dto/OrderResponseDto.java", '''\
package com.xenocrm.order.dto;

import com.xenocrm.order.enums.OrderStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

/** OrderResponseDto -- Standard API response for an order. Layer: DTO */
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class OrderResponseDto {
    private UUID id;
    private UUID customerId;
    private String orderNumber;
    private OrderStatus status;
    private String channel;
    private BigDecimal totalAmount;
    private String currency;
    private BigDecimal discountAmount;
    private String couponCode;
    private OffsetDateTime placedAt;
    private OffsetDateTime deliveredAt;
    private OffsetDateTime createdAt;
}
''')

w("order/dto/OrderCreateRequestDto.java", '''\
package com.xenocrm.order.dto;

import com.xenocrm.order.enums.OrderStatus;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/** OrderCreateRequestDto -- DTO for ingesting a new order. Layer: DTO */
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class OrderCreateRequestDto {
    @NotNull private UUID customerId;
    private String orderNumber;
    private OrderStatus status;
    private String channel;
    @NotNull private BigDecimal totalAmount;
    private String currency;
    private BigDecimal discountAmount;
    private String couponCode;
    private OffsetDateTime placedAt;
    private Map<String, Object> metadata;
    private List<OrderItemDto> items;
}
''')

w("order/dto/OrderItemDto.java", '''\
package com.xenocrm.order.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import java.math.BigDecimal;
import java.util.UUID;

/** OrderItemDto -- DTO for a line item within an order create/response. Layer: DTO */
@Data
public class OrderItemDto {
    private UUID productId;
    private String productSku;
    @NotBlank private String productName;
    @NotNull private Integer quantity;
    @NotNull private BigDecimal unitPrice;
    private BigDecimal discountAmount;
    private BigDecimal lineTotal;  // read-only GENERATED column
}
''')

w("product/dto/ProductResponseDto.java", '''\
package com.xenocrm.product.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Map;
import java.util.UUID;

/** ProductResponseDto -- Standard API response for a product. Layer: DTO */
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class ProductResponseDto {
    private UUID id;
    private String sku;
    private String name;
    private UUID categoryId;
    private String categoryName;
    private BigDecimal price;
    private String currency;
    private String brand;
    private String[] tags;
    private Map<String, Object> attributes;
    private boolean isActive;
    private OffsetDateTime createdAt;
}
''')

w("product/dto/ProductCreateRequestDto.java", '''\
package com.xenocrm.product.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.Map;
import java.util.UUID;

/** ProductCreateRequestDto -- DTO for creating a new product. Layer: DTO */
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class ProductCreateRequestDto {
    @NotBlank private String sku;
    @NotBlank private String name;
    private UUID categoryId;
    @NotNull private BigDecimal price;
    private String currency;
    private String brand;
    private String[] tags;
    private Map<String, Object> attributes;
    private boolean isActive;
}
''')

print("=== 3. ENUMS ===")

enums = {
    "customer/enums/CustomerGender.java": ("com.xenocrm.customer.enums", "CustomerGender", "MALE, FEMALE, OTHER, UNKNOWN", "gender IN (male,female,other,unknown)"),
    "customer/enums/PreferredChannel.java": ("com.xenocrm.customer.enums", "PreferredChannel", "EMAIL, WHATSAPP, SMS, RCS", "preferred_channel IN (email,whatsapp,sms,rcs)"),
    "order/enums/OrderStatus.java": ("com.xenocrm.order.enums", "OrderStatus", "PENDING, CONFIRMED, SHIPPED, DELIVERED, CANCELLED, RETURNED", "status IN orders"),
    "segment/enums/SegmentType.java": ("com.xenocrm.segment.enums", "SegmentType", "STATIC, DYNAMIC, AI_GENERATED", "type IN (static,dynamic,ai_generated)"),
    "segment/enums/SegmentStatus.java": ("com.xenocrm.segment.enums", "SegmentStatus", "DRAFT, BUILDING, READY, ARCHIVED", "status IN (draft,building,ready,archived)"),
    "campaign/enums/CampaignStatus.java": ("com.xenocrm.campaign.enums", "CampaignStatus", "DRAFT, SIMULATING, SCHEDULED, RUNNING, PAUSED, COMPLETED, CANCELLED, FAILED", "status IN campaigns"),
    "channelservice/enums/MessageChannel.java": ("com.xenocrm.channelservice.enums", "MessageChannel", "EMAIL, WHATSAPP, SMS, RCS", "Postgres ENUM message_channel"),
    "communication/enums/CommunicationStatus.java": ("com.xenocrm.communication.enums", "CommunicationStatus", "PENDING, SENT, DELIVERED, FAILED, OPENED, READ, CLICKED, CONVERTED, UNSUBSCRIBED, BOUNCED, EXPIRED", "status IN communications"),
    "channelservice/enums/ChannelCallbackEventType.java": ("com.xenocrm.channelservice.enums", "ChannelCallbackEventType", "DELIVERED, FAILED, OPENED, READ, CLICKED, CONVERTED, UNSUBSCRIBED, BOUNCED, EXPIRED", "event_type IN channel_callbacks"),
    "channelservice/enums/CallbackProcessingStatus.java": ("com.xenocrm.channelservice.enums", "CallbackProcessingStatus", "PENDING, PROCESSED, ERROR", "processing_status IN channel_callbacks"),
    "correction/enums/CorrectionTriggerType.java": ("com.xenocrm.correction.enums", "CorrectionTriggerType", "HIGH_FAILURE_RATE, LOW_OPEN_RATE, LOW_CTR, CHANNEL_TIMEOUT, BOUNCE_SPIKE, OPT_OUT_SPIKE", "trigger_type IN correction_events"),
    "correction/enums/CorrectionActionType.java": ("com.xenocrm.correction.enums", "CorrectionActionType", "SWITCH_CHANNEL, REWRITE_COPY, PAUSE_CAMPAIGN, REDUCE_FREQUENCY, ADD_FALLBACK, NO_ACTION", "action_taken IN correction_events"),
    "correction/enums/CorrectionOutcome.java": ("com.xenocrm.correction.enums", "CorrectionOutcome", "IMPROVED, NEUTRAL, WORSENED, INSUFFICIENT_DATA", "correction_outcome IN correction_events"),
    "simulator/enums/SimulationRunStatus.java": ("com.xenocrm.simulator.enums", "SimulationRunStatus", "PENDING, RUNNING, COMPLETED, FAILED", "status IN simulation_runs"),
    "memory/enums/MemoryLearningType.java": ("com.xenocrm.memory.enums", "MemoryLearningType", "COPY_STYLE, SEND_TIME, CHANNEL_PREFERENCE, FREQUENCY, OFFER_TYPE, SUBJECT_PATTERN", "learning_type IN org_memory_entries"),
    "memory/enums/TimeOfDay.java": ("com.xenocrm.memory.enums", "TimeOfDay", "MORNING, AFTERNOON, EVENING, NIGHT", "time_of_day IN org_memory_entries"),
    "agent/enums/AgentSessionStatus.java": ("com.xenocrm.agent.enums", "AgentSessionStatus", "RUNNING, COMPLETED, FAILED, PAUSED", "status IN agent_sessions"),
    "agent/enums/AgentDecisionType.java": ("com.xenocrm.agent.enums", "AgentDecisionType", "SEGMENT_QUERY, VARIANT_GENERATION, CHANNEL_SELECTION, SCHEDULE_DECISION, SEND_COMMAND, ABORT, MEMORY_LOOKUP, SIMULATION_TRIGGER, CORRECTION_TRIGGER", "decision_type IN agent_decisions"),
    "audit/enums/AuditActorType.java": ("com.xenocrm.audit.enums", "AuditActorType", "USER, AGENT, SYSTEM", "actor_type IN audit_logs"),
}

for path, (pkg, name, values, constraint) in enums.items():
    w(path, f'''\
package {pkg};

/**
 * {name} -- Domain enum for {constraint}.
 * Layer: Domain Enum
 * Converter: {name}Converter translates to/from lowercase for PostgreSQL CHECK constraints.
 */
public enum {name} {{
    {values}
}}
''')

print("=== 4. CONVERTERS ===")

converters = [
    ("customer/enums/CustomerGenderConverter.java",   "com.xenocrm.customer.enums",   "CustomerGender"),
    ("customer/enums/PreferredChannelConverter.java",  "com.xenocrm.customer.enums",   "PreferredChannel"),
    ("order/enums/OrderStatusConverter.java",          "com.xenocrm.order.enums",      "OrderStatus"),
    ("segment/enums/SegmentTypeConverter.java",        "com.xenocrm.segment.enums",    "SegmentType"),
    ("segment/enums/SegmentStatusConverter.java",      "com.xenocrm.segment.enums",    "SegmentStatus"),
    ("campaign/enums/CampaignStatusConverter.java",    "com.xenocrm.campaign.enums",   "CampaignStatus"),
    ("communication/enums/CommunicationStatusConverter.java", "com.xenocrm.communication.enums", "CommunicationStatus"),
    ("channelservice/enums/ChannelCallbackEventTypeConverter.java", "com.xenocrm.channelservice.enums", "ChannelCallbackEventType"),
    ("channelservice/enums/CallbackProcessingStatusConverter.java", "com.xenocrm.channelservice.enums", "CallbackProcessingStatus"),
    ("correction/enums/CorrectionTriggerTypeConverter.java",  "com.xenocrm.correction.enums",  "CorrectionTriggerType"),
    ("correction/enums/CorrectionActionTypeConverter.java",   "com.xenocrm.correction.enums",  "CorrectionActionType"),
    ("correction/enums/CorrectionOutcomeConverter.java",      "com.xenocrm.correction.enums",  "CorrectionOutcome"),
    ("simulator/enums/SimulationRunStatusConverter.java",     "com.xenocrm.simulator.enums",   "SimulationRunStatus"),
    ("memory/enums/MemoryLearningTypeConverter.java",         "com.xenocrm.memory.enums",      "MemoryLearningType"),
    ("memory/enums/TimeOfDayConverter.java",                  "com.xenocrm.memory.enums",      "TimeOfDay"),
    ("agent/enums/AgentSessionStatusConverter.java",          "com.xenocrm.agent.enums",       "AgentSessionStatus"),
    ("agent/enums/AgentDecisionTypeConverter.java",           "com.xenocrm.agent.enums",       "AgentDecisionType"),
    ("audit/enums/AuditActorTypeConverter.java",              "com.xenocrm.audit.enums",       "AuditActorType"),
]

for path, pkg, enum_name in converters:
    w(path, f'''\
package {pkg};

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;

/**
 * {enum_name}Converter -- JPA AttributeConverter that persists {enum_name} as lowercase
 * to satisfy PostgreSQL CHECK constraints, while Java code uses UPPERCASE enum values.
 * Layer: JPA Converter
 */
@Converter(autoApply = true)
public class {enum_name}Converter implements AttributeConverter<{enum_name}, String> {{

    /** Converts Java enum (UPPERCASE) to DB string (lowercase). */
    @Override
    public String convertToDatabaseColumn({enum_name} attribute) {{
        return attribute == null ? null : attribute.name().toLowerCase();
    }}

    /** Converts DB string (lowercase) to Java enum (UPPERCASE). */
    @Override
    public {enum_name} convertToEntityAttribute(String dbData) {{
        return dbData == null ? null : {enum_name}.valueOf(dbData.toUpperCase());
    }}
}}
''')

print("=== 5. REPOSITORIES ===")

w("customer/repository/CustomerRepository.java", '''\
package com.xenocrm.customer.repository;

import com.xenocrm.customer.entity.CustomerEntity;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * CustomerRepository -- JPA repository for CustomerEntity.
 * Layer: Repository
 */
public interface CustomerRepository extends JpaRepository<CustomerEntity, UUID> {
    /** Finds a customer by their unique email address. */
    Optional<CustomerEntity> findByEmail(String email);
    /** Finds a customer by their phone number. */
    Optional<CustomerEntity> findByPhone(String phone);
    /** Finds a customer by the brand external ID. */
    Optional<CustomerEntity> findByExternalId(String externalId);
    /** Returns all non-opted-out customers, paginated. */
    Page<CustomerEntity> findAllByIsGloballyOptedOutFalse(Pageable pageable);
    /** Finds customers whose tags array contains the given tag value. */
    @Query(value = "SELECT * FROM customers WHERE :tag = ANY(tags)", nativeQuery = true)
    List<CustomerEntity> findAllByTag(@Param("tag") String tag);
}
''')

w("customer/repository/CustomerMetricsRepository.java", '''\
package com.xenocrm.customer.repository;

import com.xenocrm.customer.entity.CustomerMetricsEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * CustomerMetricsRepository -- JPA repository for CustomerMetricsEntity.
 * Layer: Repository
 */
public interface CustomerMetricsRepository extends JpaRepository<CustomerMetricsEntity, UUID> {
    /** Finds computed metrics for a specific customer. */
    Optional<CustomerMetricsEntity> findByCustomerId(UUID customerId);
    /** Finds all customers with RFM score at or above the given minimum. */
    List<CustomerMetricsEntity> findAllByRfmScoreGreaterThanEqual(BigDecimal minimumRfmScore);
    /** Finds all customers with churn probability above the given threshold. */
    List<CustomerMetricsEntity> findAllByChurnProbabilityGreaterThan(BigDecimal threshold);
}
''')

w("campaign/repository/CampaignRepository.java", '''\
package com.xenocrm.campaign.repository;

import com.xenocrm.campaign.entity.CampaignEntity;
import com.xenocrm.campaign.enums.CampaignStatus;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * CampaignRepository -- JPA repository for CampaignEntity.
 * Layer: Repository
 * Contains atomic counter-increment queries to avoid read-modify-write race conditions.
 */
public interface CampaignRepository extends JpaRepository<CampaignEntity, UUID> {
    /** Returns all campaigns with the given status. */
    List<CampaignEntity> findAllByStatus(CampaignStatus status);
    /** Returns all campaigns created by the Sovereign Agent. */
    List<CampaignEntity> findAllByCreatedByAgentTrue();
    /** Atomically increments total_sent counter. */
    @Modifying @Transactional
    @Query("UPDATE CampaignEntity c SET c.totalSent = c.totalSent + 1 WHERE c.id = :id")
    void incrementTotalSent(@Param("id") UUID campaignId);
    /** Atomically increments total_delivered counter. */
    @Modifying @Transactional
    @Query("UPDATE CampaignEntity c SET c.totalDelivered = c.totalDelivered + 1 WHERE c.id = :id")
    void incrementTotalDelivered(@Param("id") UUID campaignId);
    /** Atomically increments total_failed counter. */
    @Modifying @Transactional
    @Query("UPDATE CampaignEntity c SET c.totalFailed = c.totalFailed + 1 WHERE c.id = :id")
    void incrementTotalFailed(@Param("id") UUID campaignId);
    /** Atomically increments total_opened counter. */
    @Modifying @Transactional
    @Query("UPDATE CampaignEntity c SET c.totalOpened = c.totalOpened + 1 WHERE c.id = :id")
    void incrementTotalOpened(@Param("id") UUID campaignId);
    /** Atomically increments total_read counter. */
    @Modifying @Transactional
    @Query("UPDATE CampaignEntity c SET c.totalRead = c.totalRead + 1 WHERE c.id = :id")
    void incrementTotalRead(@Param("id") UUID campaignId);
    /** Atomically increments total_clicked counter. */
    @Modifying @Transactional
    @Query("UPDATE CampaignEntity c SET c.totalClicked = c.totalClicked + 1 WHERE c.id = :id")
    void incrementTotalClicked(@Param("id") UUID campaignId);
    /** Atomically increments total_converted counter. */
    @Modifying @Transactional
    @Query("UPDATE CampaignEntity c SET c.totalConverted = c.totalConverted + 1 WHERE c.id = :id")
    void incrementTotalConverted(@Param("id") UUID campaignId);
    /** Queries v_campaign_performance view for one campaign performance summary. */
    @Query(value = "SELECT * FROM v_campaign_performance WHERE id = CAST(:id AS uuid)", nativeQuery = true)
    Optional<Object[]> findPerformanceSummaryById(@Param("id") String campaignId);
    /** Queries v_opt_out_alerts for all currently running campaigns. */
    @Query(value = "SELECT * FROM v_opt_out_alerts", nativeQuery = true)
    List<Object[]> findAllOptOutAlerts();
}
''')

w("variant/repository/MessageVariantRepository.java", '''\
package com.xenocrm.variant.repository;

import com.xenocrm.variant.entity.MessageVariantEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;
import java.util.UUID;

/**
 * MessageVariantRepository -- JPA repository for MessageVariantEntity.
 * Layer: Repository
 */
public interface MessageVariantRepository extends JpaRepository<MessageVariantEntity, UUID> {
    /** Returns all variants for a campaign. */
    List<MessageVariantEntity> findAllByCampaignId(UUID campaignId);
    /** Returns only active variants for a campaign (for MAB selection). */
    List<MessageVariantEntity> findAllByCampaignIdAndMabIsActiveTrue(UUID campaignId);
    /** Atomically increments mab_alpha (success). */
    @Modifying @Transactional
    @Query("UPDATE MessageVariantEntity v SET v.mabAlpha = v.mabAlpha + 1 WHERE v.id = :id")
    void incrementMabAlpha(@Param("id") UUID variantId);
    /** Atomically increments mab_beta (non-success). */
    @Modifying @Transactional
    @Query("UPDATE MessageVariantEntity v SET v.mabBeta = v.mabBeta + 1 WHERE v.id = :id")
    void incrementMabBeta(@Param("id") UUID variantId);
    /** Atomically increments mab_impressions (delivery count). */
    @Modifying @Transactional
    @Query("UPDATE MessageVariantEntity v SET v.mabImpressions = v.mabImpressions + 1 WHERE v.id = :id")
    void incrementMabImpressions(@Param("id") UUID variantId);
    /** Atomically increments mab_conversions (click/conversion count). */
    @Modifying @Transactional
    @Query("UPDATE MessageVariantEntity v SET v.mabConversions = v.mabConversions + 1 WHERE v.id = :id")
    void incrementMabConversions(@Param("id") UUID variantId);
    /** Queries v_variant_mab_stats view for Thompson Sampling statistics. */
    @Query(value = "SELECT * FROM v_variant_mab_stats WHERE campaign_id = CAST(:campaignId AS uuid)", nativeQuery = true)
    List<Object[]> findMabStatsByCampaignId(@Param("campaignId") String campaignId);
}
''')

w("segment/repository/AudienceSegmentRepository.java", '''\
package com.xenocrm.segment.repository;

import com.xenocrm.segment.entity.AudienceSegmentEntity;
import com.xenocrm.segment.enums.SegmentStatus;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import java.util.List;
import java.util.UUID;

/**
 * AudienceSegmentRepository -- JPA repository for AudienceSegmentEntity.
 * Layer: Repository
 */
public interface AudienceSegmentRepository extends JpaRepository<AudienceSegmentEntity, UUID> {
    /** Returns all segments with the given status. */
    List<AudienceSegmentEntity> findAllByStatus(SegmentStatus status);
    /** Returns all segments created by the Sovereign Agent. */
    List<AudienceSegmentEntity> findAllByCreatedByAgentTrue();
    /** Calls the fn_evaluate_segment stored function. Returns new customer_count. */
    @Query(value = "SELECT fn_evaluate_segment(CAST(:segmentId AS uuid))", nativeQuery = true)
    Integer callEvaluateSegmentFunction(@Param("segmentId") String segmentId);
}
''')

w("segment/repository/SegmentMemberRepository.java", '''\
package com.xenocrm.segment.repository;

import com.xenocrm.segment.entity.SegmentMemberEntity;
import com.xenocrm.segment.entity.SegmentMemberId;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;
import java.util.UUID;

/**
 * SegmentMemberRepository -- JPA repository for SegmentMemberEntity (composite PK).
 * Layer: Repository
 */
public interface SegmentMemberRepository extends JpaRepository<SegmentMemberEntity, SegmentMemberId> {
    /** Finds all members of a segment. */
    @Query("SELECT sm FROM SegmentMemberEntity sm WHERE sm.id.segmentId = :segmentId")
    List<SegmentMemberEntity> findAllBySegmentId(@Param("segmentId") UUID segmentId);
    /** Finds all members of a segment, paginated. */
    @Query("SELECT sm FROM SegmentMemberEntity sm WHERE sm.id.segmentId = :segmentId")
    Page<SegmentMemberEntity> findAllBySegmentId(@Param("segmentId") UUID segmentId, Pageable pageable);
    /** Deletes all members of a segment (before re-evaluation). */
    @Modifying @Transactional
    @Query("DELETE FROM SegmentMemberEntity sm WHERE sm.id.segmentId = :segmentId")
    void deleteAllBySegmentId(@Param("segmentId") UUID segmentId);
    /** Checks if a specific customer is a member of a specific segment. */
    @Query("SELECT COUNT(sm) > 0 FROM SegmentMemberEntity sm WHERE sm.id.segmentId = :segmentId AND sm.id.customerId = :customerId")
    boolean existsBySegmentIdAndCustomerId(@Param("segmentId") UUID segmentId, @Param("customerId") UUID customerId);
}
''')

w("memory/repository/OrgMemoryEntryRepository.java", '''\
package com.xenocrm.memory.repository;

import com.xenocrm.channelservice.enums.MessageChannel;
import com.xenocrm.memory.entity.OrgMemoryEntryEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.transaction.annotation.Transactional;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

/**
 * OrgMemoryEntryRepository -- JPA repository for OrgMemoryEntryEntity.
 * Layer: Repository
 */
public interface OrgMemoryEntryRepository extends JpaRepository<OrgMemoryEntryEntity, UUID> {
    /** Finds all active memory entries for a specific segment tag. */
    List<OrgMemoryEntryEntity> findAllBySegmentTagAndIsActiveTrue(String segmentTag);
    /** Finds all active memory entries for a specific channel. */
    List<OrgMemoryEntryEntity> findAllByChannelAndIsActiveTrue(MessageChannel channel);
    /** Finds all active memory entries for a specific segment tag and channel. */
    List<OrgMemoryEntryEntity> findAllBySegmentTagAndChannelAndIsActiveTrue(String segmentTag, MessageChannel channel);
    /** Deactivates all memory entries whose expiry date has passed. */
    @Modifying @Transactional
    @Query("UPDATE OrgMemoryEntryEntity m SET m.isActive = false WHERE m.expiresAt < :now")
    void deactivateExpiredEntries(@Param("now") OffsetDateTime now);
}
''')

w("agent/repository/AgentSessionRepository.java", '''\
package com.xenocrm.agent.repository;

import com.xenocrm.agent.entity.AgentSessionEntity;
import com.xenocrm.agent.enums.AgentSessionStatus;
import org.springframework.data.jpa.repository.JpaRepository;
import java.util.List;
import java.util.UUID;

/**
 * AgentSessionRepository -- JPA repository for AgentSessionEntity.
 * Layer: Repository
 */
public interface AgentSessionRepository extends JpaRepository<AgentSessionEntity, UUID> {
    /** Finds all sessions with the given status (e.g. all RUNNING sessions). */
    List<AgentSessionEntity> findAllByStatus(AgentSessionStatus status);
}
''')

w("agent/repository/AgentDecisionRepository.java", '''\
package com.xenocrm.agent.repository;

import com.xenocrm.agent.entity.AgentDecisionEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import java.util.List;
import java.util.UUID;

/**
 * AgentDecisionRepository -- JPA repository for AgentDecisionEntity.
 * Layer: Repository
 */
public interface AgentDecisionRepository extends JpaRepository<AgentDecisionEntity, UUID> {
    /** Finds all decisions for a session in chronological step order. */
    List<AgentDecisionEntity> findAllBySessionIdOrderByStepNumberAsc(UUID sessionId);
}
''')

w("audit/repository/AuditLogRepository.java", '''\
package com.xenocrm.audit.repository;

import com.xenocrm.audit.entity.AuditLogEntity;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import java.util.UUID;

/**
 * AuditLogRepository -- JPA repository for AuditLogEntity.
 * Layer: Repository
 */
public interface AuditLogRepository extends JpaRepository<AuditLogEntity, Long> {
    /** Finds all audit logs for a specific entity type and ID, paginated. */
    Page<AuditLogEntity> findAllByEntityTypeAndEntityId(String entityType, Long entityId, Pageable pageable);
    /** Finds all audit logs belonging to a request trace ID, paginated. */
    Page<AuditLogEntity> findAllByTraceId(UUID traceId, Pageable pageable);
    /** Finds all audit logs by actor (API key hash, agent session ID, etc.), paginated. */
    Page<AuditLogEntity> findAllByActorId(String actorId, Pageable pageable);
}
''')

print("=== 6. MAPPERS ===")

w("customer/mapper/CustomerMapper.java", '''\
package com.xenocrm.customer.mapper;

import com.xenocrm.customer.dto.Customer360ResponseDto;
import com.xenocrm.customer.dto.CustomerCreateRequestDto;
import com.xenocrm.customer.dto.CustomerResponseDto;
import com.xenocrm.customer.dto.CustomerUpdateRequestDto;
import com.xenocrm.customer.entity.CustomerEntity;
import com.xenocrm.customer.entity.CustomerMetricsEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

/**
 * CustomerMapper -- MapStruct mapper for Customer domain.
 * Layer: Mapper
 */
@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface CustomerMapper {
    /** Converts a create request DTO to a CustomerEntity. */
    CustomerEntity toEntity(CustomerCreateRequestDto dto);
    /** Partially updates an existing CustomerEntity from an update DTO (null fields ignored). */
    void updateEntityFromDto(CustomerUpdateRequestDto dto, @MappingTarget CustomerEntity entity);
    /** Converts a CustomerEntity to a standard response DTO. */
    CustomerResponseDto toResponseDto(CustomerEntity entity);
    /** Combines CustomerEntity and CustomerMetricsEntity into a 360 view DTO. */
    @Mapping(target = "id",                   source = "customer.id")
    @Mapping(target = "externalId",           source = "customer.externalId")
    @Mapping(target = "email",                source = "customer.email")
    @Mapping(target = "phone",                source = "customer.phone")
    @Mapping(target = "whatsappNumber",       source = "customer.whatsappNumber")
    @Mapping(target = "name",                 source = "customer.name")
    @Mapping(target = "gender",               source = "customer.gender")
    @Mapping(target = "dateOfBirth",          source = "customer.dateOfBirth")
    @Mapping(target = "city",                 source = "customer.city")
    @Mapping(target = "state",                source = "customer.state")
    @Mapping(target = "country",              source = "customer.country")
    @Mapping(target = "tags",                 source = "customer.tags")
    @Mapping(target = "customAttributes",     source = "customer.customAttributes")
    @Mapping(target = "preferredChannel",     source = "customer.preferredChannel")
    @Mapping(target = "optOutChannels",       source = "customer.optOutChannels")
    @Mapping(target = "isGloballyOptedOut",   source = "customer.globallyOptedOut")
    @Mapping(target = "createdAt",            source = "customer.createdAt")
    @Mapping(target = "updatedAt",            source = "customer.updatedAt")
    @Mapping(target = "recencyDays",          source = "metrics.recencyDays")
    @Mapping(target = "frequency",            source = "metrics.frequency")
    @Mapping(target = "monetaryTotal",        source = "metrics.monetaryTotal")
    @Mapping(target = "monetaryAvgOrder",     source = "metrics.monetaryAvgOrder")
    @Mapping(target = "rfmScore",             source = "metrics.rfmScore")
    @Mapping(target = "totalOrdersLast30d",   source = "metrics.totalOrdersLast30d")
    @Mapping(target = "totalOrdersLast90d",   source = "metrics.totalOrdersLast90d")
    @Mapping(target = "avgDaysBetweenOrders", source = "metrics.avgDaysBetweenOrders")
    @Mapping(target = "favouriteCategoryId",  source = "metrics.favouriteCategoryId")
    @Mapping(target = "favouriteChannel",     source = "metrics.favouriteChannel")
    @Mapping(target = "clvPredicted",         source = "metrics.clvPredicted")
    @Mapping(target = "churnProbability",     source = "metrics.churnProbability")
    @Mapping(target = "emailOpenRate",        source = "metrics.emailOpenRate")
    @Mapping(target = "emailClickRate",       source = "metrics.emailClickRate")
    @Mapping(target = "whatsappReadRate",     source = "metrics.whatsappReadRate")
    @Mapping(target = "smsClickRate",         source = "metrics.smsClickRate")
    @Mapping(target = "lastComputedAt",       source = "metrics.lastComputedAt")
    Customer360ResponseDto to360ResponseDto(CustomerEntity customer, CustomerMetricsEntity metrics);
}
''')

w("campaign/mapper/CampaignMapper.java", '''\
package com.xenocrm.campaign.mapper;

import com.xenocrm.campaign.dto.CampaignCreateRequestDto;
import com.xenocrm.campaign.dto.CampaignResponseDto;
import com.xenocrm.campaign.entity.CampaignEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.NullValuePropertyMappingStrategy;

/**
 * CampaignMapper -- MapStruct mapper for Campaign domain.
 * Layer: Mapper
 */
@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface CampaignMapper {
    /** Converts a create request DTO to a CampaignEntity (segment/parent set in service). */
    @Mapping(target = "targetSegment", ignore = true)
    @Mapping(target = "parentCampaign", ignore = true)
    CampaignEntity toEntity(CampaignCreateRequestDto dto);
    /** Converts a CampaignEntity to a standard response DTO. */
    @Mapping(target = "segmentId",        source = "targetSegment.id")
    @Mapping(target = "segmentName",      source = "targetSegment.name")
    @Mapping(target = "parentCampaignId", source = "parentCampaign.id")
    CampaignResponseDto toResponseDto(CampaignEntity campaign);
}
''')

w("variant/mapper/MessageVariantMapper.java", '''\
package com.xenocrm.variant.mapper;

import com.xenocrm.variant.dto.MessageVariantCreateRequestDto;
import com.xenocrm.variant.dto.MessageVariantResponseDto;
import com.xenocrm.variant.entity.MessageVariantEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.NullValuePropertyMappingStrategy;

/**
 * MessageVariantMapper -- MapStruct mapper for MessageVariant domain.
 * Layer: Mapper
 */
@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface MessageVariantMapper {
    /** Converts a create request DTO to a MessageVariantEntity (campaign set in service). */
    @Mapping(target = "campaign", ignore = true)
    MessageVariantEntity toEntity(MessageVariantCreateRequestDto dto);
    /** Converts a MessageVariantEntity to a standard response DTO. */
    @Mapping(target = "campaignId", source = "campaign.id")
    MessageVariantResponseDto toResponseDto(MessageVariantEntity entity);
}
''')

w("order/mapper/OrderMapper.java", '''\
package com.xenocrm.order.mapper;

import com.xenocrm.order.dto.OrderCreateRequestDto;
import com.xenocrm.order.dto.OrderResponseDto;
import com.xenocrm.order.entity.OrderEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.NullValuePropertyMappingStrategy;

/**
 * OrderMapper -- MapStruct mapper for Order domain.
 * Layer: Mapper
 */
@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface OrderMapper {
    /** Converts a create request DTO to an OrderEntity (customer set in service). */
    @Mapping(target = "customer", ignore = true)
    @Mapping(target = "orderItems", ignore = true)
    OrderEntity toEntity(OrderCreateRequestDto dto);
    /** Converts an OrderEntity to a standard response DTO. */
    @Mapping(target = "customerId", source = "customer.id")
    OrderResponseDto toResponseDto(OrderEntity entity);
}
''')

w("product/mapper/ProductMapper.java", '''\
package com.xenocrm.product.mapper;

import com.xenocrm.product.dto.ProductCreateRequestDto;
import com.xenocrm.product.dto.ProductResponseDto;
import com.xenocrm.product.entity.ProductEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.NullValuePropertyMappingStrategy;

/**
 * ProductMapper -- MapStruct mapper for Product domain.
 * Layer: Mapper
 */
@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface ProductMapper {
    /** Converts a create request DTO to a ProductEntity (category set in service). */
    @Mapping(target = "category", ignore = true)
    ProductEntity toEntity(ProductCreateRequestDto dto);
    /** Converts a ProductEntity to a standard response DTO. */
    @Mapping(target = "categoryId",   source = "category.id")
    @Mapping(target = "categoryName", source = "category.name")
    ProductResponseDto toResponseDto(ProductEntity entity);
}
''')

print("=== 7. APPLICATION.YML ===")
yml_path = r"c:\Users\Sarishma\Project-Xeno\xenon-backend\src\main\resources\application.yml"
with open(yml_path, "w", encoding="utf-8") as f:
    f.write("""\
spring:
  application:
    name: xeno-crm-backend

  datasource:
    url: jdbc:postgresql://db.${SUPABASE_PROJECT_ID}.supabase.co:5432/postgres
    username: postgres
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  config:
    import: optional:classpath:application-local.properties

server:
  port: 8080

# Gemini LLM
gemini:
  api-key: ${gemini.api-key}
  model: gemini-2.5-pro
  endpoint: https://generativelanguage.googleapis.com/v1beta/models
  max-output-tokens: 2000
  temperature: 0.3

# Channel stub
channel:
  stub:
    base-url: http://localhost:8081
  crm:
    callback-url: http://localhost:8080/api/v1/callbacks/channel

# Security
security:
  api-key: ${CRM_API_KEY}

# Async thread pool
async:
  core-pool-size: 10
  max-pool-size: 50
  queue-capacity: 500

# Self-correction thresholds
correction:
  failure-rate-threshold: 0.30
  low-open-rate-threshold: 0.05
  opt-out-rate-threshold: 0.02
  evaluation-window-minutes: 10

logging:
  level:
    com.xenocrm: DEBUG

---
# Channel stub profile -- runs on port 8081
spring:
  config:
    activate:
      on-profile: stub
server:
  port: 8081
""")
print("  wrote: application.yml")

print("=== ALL DONE ===")
