"use client";

import { Shell } from "@/components/layout/Shell";
import { Button } from "@/components/ui/button";
import { Bot, Brain, Users, ThumbsDown, ThumbsUp, Loader2, CheckCircle, XCircle, DollarSign, ExternalLink } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { useState } from "react";
import { toast } from "sonner";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function ProposalsInbox() {
  const queryClient = useQueryClient();
  const router = useRouter();
  const [currentIndex, setCurrentIndex] = useState(0);
  // Optimistic local state: track IDs that have been actioned so they disappear immediately
  const [actionedIds, setActionedIds] = useState<Set<string>>(new Set());
  const [lastApprovedId, setLastApprovedId] = useState<string | null>(null);

  const { data: proposalsData, isLoading } = useQuery({
    queryKey: ['campaigns', 'proposals'],
    queryFn: () => api.get(`/campaigns/proposals`).then(res => Array.isArray(res) ? res : res?.content || []),
    retry: false,
    staleTime: 15_000,
  });

  // Fetch ALL campaigns to compute real stats
  const { data: allCampaigns } = useQuery({
    queryKey: ['campaigns'],
    queryFn: () => api.get('/campaigns').then(res => Array.isArray(res) ? res : res?.content || []),
    staleTime: 30_000,
  });

  const allCampaignsList: any[] = Array.isArray(allCampaigns) ? allCampaigns : [];
  const rawProposals: any[] = Array.isArray(proposalsData) ? proposalsData : [];

  // Filter out actioned proposals optimistically
  const proposals = rawProposals.filter(p => !actionedIds.has(p.id));
  const currentProposal = proposals[Math.min(currentIndex, proposals.length - 1)];

  // Stats derived from all campaigns
  const thisMonth = new Date();
  thisMonth.setDate(1);
  thisMonth.setHours(0, 0, 0, 0);
  const approvedThisMonth = allCampaignsList.filter(c =>
    c.createdByAgent && (c.status === 'RUNNING' || c.status === 'COMPLETED' || c.status === 'APPROVED' || c.status === 'SCHEDULED') &&
    new Date(c.createdAt) >= thisMonth
  ).length;
  const rejectedCount = allCampaignsList.filter(c =>
    c.createdByAgent && (c.status === 'CANCELLED' || c.status === 'REJECTED')
  ).length;
  const revenueFromAI = allCampaignsList
    .filter(c => c.createdByAgent)
    .reduce((sum: number, c: any) => sum + (c.revenueAttributed || c.totalRevenue || 0), 0);

  const approveMutation = useMutation({
    mutationFn: (id: string) => api.post(`/campaigns/${id}/approve`),
    onSuccess: (_data, id) => {
      setActionedIds(prev => new Set([...prev, id]));
      setLastApprovedId(id);
      toast.success("Campaign approved and launched!", {
        action: {
          label: "View Campaign",
          onClick: () => router.push(`/campaigns/${id}`),
        },
      });
      queryClient.invalidateQueries({ queryKey: ['campaigns', 'proposals'] });
      queryClient.invalidateQueries({ queryKey: ['campaigns'] });
      // move index down if needed
      setCurrentIndex(prev => Math.max(0, prev - 1));
    },
    onError: (err: any) => toast.error(err.message || "Failed to approve campaign.")
  });

  const rejectMutation = useMutation({
    mutationFn: (id: string) => api.patch(`/campaigns/${id}/status`, { status: 'CANCELLED' }),
    onSuccess: (_data, id) => {
      setActionedIds(prev => new Set([...prev, id]));
      toast.success("Proposal rejected.");
      queryClient.invalidateQueries({ queryKey: ['campaigns', 'proposals'] });
      queryClient.invalidateQueries({ queryKey: ['campaigns'] });
      setCurrentIndex(prev => Math.max(0, prev - 1));
    },
    onError: (err: any) => toast.error(err.message || "Failed to reject.")
  });

  return (
    <Shell title="AI Proposals">
      <div className="flex items-start justify-between mb-6 -mt-2">
        <div>
          <h2 className="text-[18px] font-medium text-text-primary mb-1 flex items-center gap-2">
            AI Proposals
            <Badge className="bg-blue-50 text-blue-700 hover:bg-blue-50 font-medium text-[12px] px-2.5 py-0.5 gap-1.5">
              <Bot className="w-3.5 h-3.5"/> {proposals.length} awaiting review
            </Badge>
          </h2>
          <p className="text-[13px] text-text-secondary">Campaigns autonomously generated by the Sovereign AI Agent. Review and approve to launch.</p>
        </div>
        {lastApprovedId && (
          <Link href={`/campaigns/${lastApprovedId}`}>
            <Button variant="outline" size="sm" className="h-8 text-[13px] gap-2 text-green-700 border-green-200 hover:bg-green-50">
              <ExternalLink className="w-4 h-4" /> View Last Approved
            </Button>
          </Link>
        )}
      </div>

      {/* Stats Row */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        <div className="bg-green-50 border border-green-100 rounded-xl p-4 text-center">
          <div className="flex items-center justify-center gap-1.5 mb-1">
            <CheckCircle className="w-4 h-4 text-green-600" />
            <div className="text-[22px] font-semibold text-green-700">{approvedThisMonth}</div>
          </div>
          <div className="text-[11px] text-green-600">Approved this month</div>
        </div>
        <div className="bg-red-50 border border-red-100 rounded-xl p-4 text-center">
          <div className="flex items-center justify-center gap-1.5 mb-1">
            <XCircle className="w-4 h-4 text-red-600" />
            <div className="text-[22px] font-semibold text-red-700">{rejectedCount}</div>
          </div>
          <div className="text-[11px] text-red-600">Rejected</div>
        </div>
        <div className="bg-brand-light border border-brand/10 rounded-xl p-4 text-center">
          <div className="flex items-center justify-center gap-1.5 mb-1">
            <DollarSign className="w-4 h-4 text-brand" />
            <div className="text-[22px] font-semibold text-brand">
              ${revenueFromAI >= 1000 ? `${(revenueFromAI / 1000).toFixed(1)}K` : revenueFromAI.toFixed(0)}
            </div>
          </div>
          <div className="text-[11px] text-brand">Revenue from AI proposals</div>
        </div>
      </div>

      {isLoading ? (
        <div className="flex justify-center items-center py-20">
          <Loader2 className="w-8 h-8 text-brand animate-spin" />
        </div>
      ) : proposals.length === 0 ? (
        <div className="bg-bg-secondary border border-border-primary rounded-xl p-12 text-center">
          <Bot className="w-12 h-12 text-text-tertiary mx-auto mb-4" />
          <h3 className="text-[16px] font-medium text-text-primary mb-1">Inbox Zero</h3>
          <p className="text-[13px] text-text-secondary">The Sovereign AI has no pending campaign proposals right now.</p>
          <Link href="/agent" className="mt-4 inline-block">
            <Button variant="outline" size="sm" className="mt-4 gap-2">
              <Bot className="w-4 h-4" /> Ask AI to create one
            </Button>
          </Link>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_340px] gap-6">

          {/* Main Tinder Swipe UI */}
          <div>
             <div className="flex items-center justify-between text-[12px] text-text-secondary mb-3">
               <span><strong>{Math.min(currentIndex + 1, proposals.length)} of {proposals.length}</strong> proposals · click to review</span>
               <div className="flex gap-1">
                 {proposals.map((_: any, i: number) => (
                   <div key={i} className={`w-5 h-1 rounded-full ${i === currentIndex ? 'bg-text-primary' : 'bg-border-tertiary'}`} />
                 ))}
               </div>
             </div>

             {currentProposal && (
               <div className="bg-white border border-border-primary rounded-xl p-6 shadow-minimal relative hover:-translate-y-px transition-transform">
                 <div className="flex items-center gap-3 pb-4 mb-4 border-b border-border-tertiary">
                   <div className="w-10 h-10 rounded-xl bg-brand-light text-brand flex items-center justify-center shrink-0">
                     <Brain className="w-5 h-5" />
                   </div>
                   <div>
                     <div className="text-[11px] text-text-tertiary font-medium uppercase tracking-wider mb-0.5">Sovereign AI · Created {new Date(currentProposal.createdAt).toLocaleTimeString()}</div>
                     <div className="text-[16px] font-medium text-text-primary">{currentProposal.name}</div>
                   </div>
                 </div>

                 <div className="flex items-center gap-2 mb-4 flex-wrap">
                   <Badge variant="outline" className="text-[12px] font-normal bg-bg-secondary text-text-secondary gap-1.5 py-1 px-3">
                     <Users className="w-3.5 h-3.5"/> Segment Target
                   </Badge>
                   <Badge className="bg-green-50 text-green-700 hover:bg-green-50 font-medium">Auto-Channel Optimization</Badge>
                   <Badge className="bg-blue-50 text-blue-700 hover:bg-blue-50 font-medium">{currentProposal.status || 'DRAFT'}</Badge>
                 </div>

                 <div className="bg-bg-secondary rounded-xl p-4 text-[13px] text-text-secondary leading-relaxed border-l-4 border-brand-light mb-5">
                   <strong className="text-text-primary font-medium">AI Goal:</strong> {currentProposal.goal || 'Autonomous campaign optimisation based on segment analytics.'}
                   {currentProposal.segmentName && <div className="mt-1">Target Segment: <span className="font-medium text-text-primary">{currentProposal.segmentName}</span></div>}
                 </div>

                 {currentProposal.description && (
                   <div className="text-[13px] text-text-secondary mb-4 bg-bg-secondary px-3 py-2 rounded-lg">
                     <strong className="text-text-primary font-medium">Description:</strong> &quot;{currentProposal.description}&quot;
                   </div>
                 )}

                 <div className="flex gap-3">
                   <Button
                     variant="outline"
                     className="flex-1 border-red-200 text-red-600 hover:bg-red-50 hover:text-red-700 h-12 text-[14px] gap-2"
                     onClick={() => rejectMutation.mutate(currentProposal.id)}
                     disabled={rejectMutation.isPending || approveMutation.isPending}
                   >
                     {rejectMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <ThumbsDown className="w-4 h-4"/>}
                     Reject
                   </Button>
                   <Button
                     className="flex-[2] h-12 text-[14px] gap-2 bg-text-primary text-white hover:bg-black/90"
                     onClick={() => approveMutation.mutate(currentProposal.id)}
                     disabled={rejectMutation.isPending || approveMutation.isPending}
                   >
                     {approveMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <ThumbsUp className="w-4 h-4"/>}
                     Approve &amp; launch
                   </Button>
                 </div>
               </div>
             )}

             {/* Navigation arrows if multiple proposals */}
             {proposals.length > 1 && (
               <div className="flex gap-2 mt-3 justify-center">
                 <Button variant="outline" size="sm" className="h-7 text-[11px]" disabled={currentIndex === 0} onClick={() => setCurrentIndex(p => p - 1)}>← Previous</Button>
                 <Button variant="outline" size="sm" className="h-7 text-[11px]" disabled={currentIndex >= proposals.length - 1} onClick={() => setCurrentIndex(p => p + 1)}>Next →</Button>
               </div>
             )}
          </div>

          {/* Sidebar */}
          <div className="flex flex-col gap-6">

            {/* Pending List */}
            <div className="bg-white border border-border-primary rounded-xl overflow-hidden shadow-minimal">
              <div className="bg-bg-secondary px-4 py-3 border-b border-border-tertiary text-[13px] font-medium text-text-primary">
                All pending proposals ({proposals.length})
              </div>
              {proposals.map((p: any, i: number) => (
                <div
                  key={p.id}
                  onClick={() => setCurrentIndex(i)}
                  className={`flex items-center gap-3 px-4 py-3 border-b border-border-tertiary last:border-0 cursor-pointer hover:bg-bg-secondary ${i === currentIndex ? 'bg-bg-secondary' : ''}`}
                >
                  <div className={`w-2 h-2 rounded-full shrink-0 ${i === currentIndex ? 'bg-brand' : 'bg-border-secondary'}`} />
                  <div className="flex-1 min-w-0">
                    <div className="text-[13px] text-text-primary truncate">{p.name}</div>
                    <div className="text-[11px] text-text-tertiary mt-0.5">{p.goal?.substring(0, 50) || 'No goal set'}{p.goal?.length > 50 ? '...' : ''}</div>
                  </div>
                </div>
              ))}
            </div>

            {/* Quick Nav to active campaigns */}
            <Link href="/campaigns">
              <div className="bg-brand-light border border-brand/10 rounded-xl px-4 py-3 flex items-center gap-3 cursor-pointer hover:bg-brand/10 transition-colors">
                <CheckCircle className="w-4 h-4 text-brand shrink-0" />
                <div>
                  <div className="text-[13px] font-medium text-brand">View Active Campaigns</div>
                  <div className="text-[11px] text-brand/70">See all approved &amp; running campaigns</div>
                </div>
              </div>
            </Link>
          </div>
        </div>
      )}
    </Shell>
  );
}
