package com.xenocrm.customer.entity;

import com.xenocrm.customer.enums.CustomerGender;
import com.xenocrm.customer.enums.PreferredChannel;
import io.hypersistence.utils.hibernate.type.array.StringArrayType;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.Type;
import org.hibernate.type.SqlTypes;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * CustomerEntity -- JPA entity mapping to the `customers` table.
 * Layer: Domain Entity
 * Purpose: Represents the core identity record for every shopper.
 * Relationships: OneToOne CustomerMetricsEntity; OneToMany OrderEntity.
 */
@Entity
@Table(name = "customers")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class CustomerEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id")
    private UUID id;                            // PRIMARY KEY, generated by DB

    @Column(name = "external_id", unique = true)
    private String externalId;                  // Brand own customer ID -- nullable, UNIQUE

    @Column(name = "email", unique = true)
    private String email;                       // Customer email -- nullable, UNIQUE

    @Column(name = "phone")
    private String phone;                       // E.164 format e.g. +919876543210 -- nullable

    @Column(name = "whatsapp_number")
    private String whatsappNumber;              // WhatsApp number if different from phone -- nullable

    @Column(name = "name", nullable = false)
    private String name;                        // Full name -- required

    
    @Column(name = "gender")
    private CustomerGender gender;              // CHECK IN (male,female,other,unknown) DEFAULT unknown

    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;              // Date of birth -- nullable

    @Column(name = "city")
    private String city;                        // City name -- nullable

    @Column(name = "state")
    private String state;                       // State/province -- nullable

    @Column(name = "country")
    private String country;                     // ISO country code DEFAULT IN

    @Type(StringArrayType.class)
    @Column(name = "tags", columnDefinition = "text[]")
    private String[] tags;                      // TEXT[] DEFAULT {}

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "custom_attributes", columnDefinition = "jsonb")
    private Map<String, Object> customAttributes; // JSONB -- brand-specific metadata

    
    @Column(name = "preferred_channel")
    private PreferredChannel preferredChannel;  // CHECK IN (email,whatsapp,sms,rcs)

    @Type(StringArrayType.class)
    @Column(name = "opt_out_channels", columnDefinition = "text[]")
    private String[] optOutChannels;            // TEXT[] -- channels this customer has opted out from

    @Column(name = "is_globally_opted_out", nullable = false)
    private boolean isGloballyOptedOut;         // DEFAULT FALSE -- skip entirely if true

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    @OneToOne(mappedBy = "customer", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private CustomerMetricsEntity metrics;      // computed metrics -- lazy loaded

    @OneToMany(mappedBy = "customer", fetch = FetchType.LAZY)
    private List<com.xenocrm.order.entity.OrderEntity> orders; // purchase history -- lazy loaded
}
