
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=postgres.fkuqrsthtqcymejapuqy
spring.datasource.password=Likhith@123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gemini.api-key=AQ.Ab8RN6KD9rE2Mbz9aR8LSLtbNEOGQwIivMJB3EmfB2qYLkzv3Q
# JWT Configuration
jwt.secret=K8xP4mN9qR2vT7yW5zB1cD6fG3hJ8kL4nQ9sX2eV7uY5iO1pA6rT3wE8mZ4cN7b
jwt.expiration=86400000